package main

import "fmt"

/*
 * https://projecteuler.net/problem=2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

func findSum(maximum int) (sum int) {
	for i, j := 1, 2; i < maximum; i, j = j, i+j {
		if i%2 == 0 {
			sum += i
		}
	}
	return
}

func main() {
	fmt.Println(findSum(90))
	fmt.Println(findSum(4000000))
}
